version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps)"
    target-branch: "update-dependencies"
    open-pull-requests-limit: 10
    groups:
      bundle-stats:
        patterns:
          - "@bundle-stats/*"
      eslint:
        patterns:
          - "eslint"
          - "@eslint/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
    target-branch: "master"
