name: ci
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Cache packages when the branch is not update-dependencies or dependabot/*
      - name: Resolve caching
        id: cache
        if: ${{ github.ref_name != 'update-dependencies' && !startsWith(github.ref_name, 'dependabot/') }}
        run: echo "PACKAGE=npm" >> $GITHUB_OUTPUT

      - name: Use Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version-file: ".nvmrc"
          cache: ${{ steps.cache.outputs.PACKAGE }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Cache packages when the branch is not update-dependencies or dependabot/*
      - name: Resolve caching
        id: cache
        if: ${{ github.ref_name != 'update-dependencies' && !startsWith(github.ref_name, 'dependabot/') }}
        run: echo "PACKAGE=npm" >> $GITHUB_OUTPUT

      - name: Use Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version-file: ".nvmrc"
          cache: ${{ steps.cache.outputs.PACKAGE }}

      - name: Install dependencies
        run: npm ci

      - name: Unit tests
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - uses: actions/checkout@v4

      # Cache packages when the branch is not update-dependencies or dependabot/*
      - name: Resolve caching
        id: cache
        if: ${{ github.ref_name != 'update-dependencies' && !startsWith(github.ref_name, 'dependabot/') }}
        run: echo "PACKAGE=npm" >> $GITHUB_OUTPUT

      - name: Use Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version-file: ".nvmrc"
          cache: ${{ steps.cache.outputs.PACKAGE }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload dist files
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          retention-days: 1
          path: |
            lib*/**/*

      # Publish new version to local registry
      - name: Run local npm registry
        run: ./scripts/local-registry.sh &

      - name: Publish package locally
        run: npm publish

      - name: Upload local registry files
        uses: actions/upload-artifact@v4.6.1
        with:
          name: local-registry
          retention-days: 1
          include-hidden-files: true
          path: |
            .verdaccio-storage*/**/*


  test-package-cli:
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        node: [20, 18, 16, 14]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install --package-lock false

      - name: Download dist files
        uses: actions/download-artifact@v4
        with:
          name: dist-files

      - name: Download local registry files
        uses: actions/download-artifact@v4.1.9
        with:
          name: local-registry

      - name: Run local npm registry
        run: ./scripts/local-registry.sh &

      - name: Test CLI
        run: npm run test:package-cli

  test-package-webpack-plugin:
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        node: [20, 18, 16, 14]
        webpack: ['webpack4', 'webpack5']
        exclude:
          - webpack: 'webpack4'
            node: 18
          - webpack: 'webpack4'
            node: 20
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install --package-lock false

      - name: Download dist files
        uses: actions/download-artifact@v4
        with:
          name: dist-files

      - name: Download local registry files
        uses: actions/download-artifact@v4.1.9
        with:
          name: local-registry

      - name: Run local npm registry
        run: ./scripts/local-registry.sh &

      - name: Test webpack-plugin
        run: npm run test:package-webpack-plugin -- -t ${{ matrix.webpack }}

  tests:
    needs:
      - test-package-cli
      - test-package-webpack-plugin
    runs-on: ubuntu-latest
    steps:
      - run: echo "Tests done"

  publish:
    # Run only for version tags
    if: contains(github.ref, 'refs/tags/v')
    needs:
      - tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      # Cache packages when the branch is not update-dependencies or dependabot/*
      - name: Resolve caching
        id: cache
        if: ${{ github.ref_name != 'update-dependencies' && !startsWith(github.ref_name, 'dependabot/') }}
        run: echo "PACKAGE=npm" >> $GITHUB_OUTPUT

      - name: Use Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version-file: ".nvmrc"
          cache: ${{ steps.cache.outputs.PACKAGE }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Download dist files
        uses: actions/download-artifact@v4
        with:
          name: dist-files

      - name: Publish
        run: npm run release
        env:
          NPM_CONFIG_PROVENANCE: true
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
