name: ci
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup node & npm
        uses: relative-ci/.github/actions/setup-node-npm@v1.1.5

      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup node & npm
        uses: relative-ci/.github/actions/setup-node-npm@v1.1.5

      - name: Unit tests
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - uses: actions/checkout@v5

      - name: Setup node & npm
        uses: relative-ci/.github/actions/setup-node-npm@v1.1.5

      - name: Build
        run: npm run build

      - name: Upload build files
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build-files
          retention-days: 1
          # add glob on the first directory to force paths relative to current directory
          path: |
            packages*/*/lib

      # Publish new version to local registry
      - name: Run local npm registry
        run: ./scripts/local-registry.sh &

      - name: Publish package locally
        run: ./scripts/local-registry-publish.sh

      - name: Upload local registry files
        uses: actions/upload-artifact@v4.6.2
        with:
          name: local-registry
          retention-days: 1
          include-hidden-files: true
          path: |
            .verdaccio-storage*/**/*

  test-package-cli:
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        node: [24, 22, 20, 18]
    steps:
      - uses: actions/checkout@v5

      - name: Setup node & npm
        uses: relative-ci/.github/actions/setup-node-npm@main
        with:
          version: ${{ matrix.node }}
          cache: never
          install: false

      - name: Install dependencies
        run: npm install --package-lock false

      - name: Download build files
        uses: actions/download-artifact@v5.0.0
        with:
          name: build-files

      - name: Download local registry files
        uses: actions/download-artifact@v5.0.0
        with:
          name: local-registry

      - name: Run local npm registry
        run: ./scripts/local-registry.sh &

      - name: Test CLI
        run: npm run test:package-cli

  test-package-webpack-plugin:
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        node: [24, 22, 20, 18]
        webpack: ['webpack4', 'webpack5']
    steps:
      - uses: actions/checkout@v5

      - name: Setup node & npm
        uses: relative-ci/.github/actions/setup-node-npm@main
        with:
          version: ${{ matrix.node }}
          cache: never
          install: false

      - name: Delete obsolete always-auth
        run: npm config delete always-auth

      - name: Install dependencies
        run: npm install --package-lock false

      - name: Download build files
        uses: actions/download-artifact@v5.0.0
        with:
          name: build-files

      - name: Download local registry files
        uses: actions/download-artifact@v5.0.0
        with:
          name: local-registry

      - name: Run local npm registry
        run: ./scripts/local-registry.sh &

      - name: Test webpack-plugin
        run: npm run test:package-webpack-plugin -- -t ${{ matrix.webpack }}

  tests:
    needs:
      - test-package-cli
      - test-package-webpack-plugin
    runs-on: ubuntu-latest
    steps:
      - run: echo "Tests done"

  publish:
    # Run only for version tags
    if: contains(github.ref, 'refs/tags/v')
    needs:
      - tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5

      - name: Setup node & npm
        uses: relative-ci/.github/actions/setup-node-npm@v1.1.5

      - name: Download build files
        uses: actions/download-artifact@v5.0.0
        with:
          name: build-files

      - name: Publish
        run: npm run release
        env:
          NPM_CONFIG_PROVENANCE: true
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
